-- ===================================================
-- ROLEX LUXURY WATCHES DATABASE SCHEMA (SUPABASE SQL)
-- ===================================================
-- Supabase SQL Editor me ye code paste karke "RUN" dabayein.

-- 1. Create watches table
CREATE TABLE IF NOT EXISTS public.watches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    reference_number VARCHAR(100),
    category VARCHAR(100) DEFAULT 'Classic',
    price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'USD',
    image_url TEXT NOT NULL,
    description TEXT,
    dial_color VARCHAR(100),
    case_material VARCHAR(100),
    bracelet_material VARCHAR(100),
    movement VARCHAR(100) DEFAULT 'Automatic',
    is_featured BOOLEAN DEFAULT false,
    in_stock BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create inquiries / newsletter table (optional for contact & VIP subscribers)
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    message TEXT,
    watch_id BIGINT REFERENCES public.watches(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.watches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies to allow public read & write access with Anon Key
-- Watches policies
CREATE POLICY "Public Read Access for Watches" 
ON public.watches FOR SELECT USING (true);

CREATE POLICY "Public Insert Access for Watches" 
ON public.watches FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Update Access for Watches" 
ON public.watches FOR UPDATE USING (true);

CREATE POLICY "Public Delete Access for Watches" 
ON public.watches FOR DELETE USING (true);

-- Inquiries policies
CREATE POLICY "Public Insert Access for Inquiries" 
ON public.inquiries FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Access for Inquiries" 
ON public.inquiries FOR SELECT USING (true);
